AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    BinaryMediaTypes:
    - '*~1*'
Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/uploadImage.handler
      Runtime: nodejs20.x
      Timeout: 300
      Policies:
      - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-images-bucket
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: post
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/f0345d2e8ada22d9e5ab9e3c636a1372
    Metadata:
      SamResourceId: UploadImageFunction
  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/viewImage.handler
      Runtime: nodejs20.x
      Timeout: 300
      Policies:
      - AmazonS3ReadOnlyAccess
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /viewImage
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/f0345d2e8ada22d9e5ab9e3c636a1372
    Metadata:
      SamResourceId: ViewImageFunction
  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/deleteImage.handler
      Runtime: nodejs20.x
      Timeout: 300
      Policies:
      - AmazonS3FullAccess
      Events:
        DeleteImageApi:
          Type: Api
          Properties:
            Path: /deleteImage
            Method: delete
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/f0345d2e8ada22d9e5ab9e3c636a1372
    Metadata:
      SamResourceId: DeleteImageFunction
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nelson-images-bucket
    Metadata:
      SamResourceId: ImageBucket
Outputs:
  ImageBucketName:
    Value: nelson-images-bucket
    Description: Nome do bucket S3 para armazenamento de imagens
