AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'''
      AllowOrigin: '''*'''
      AllowCredentials: '''true'''
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
      - '*~1*'
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
    Metadata:
      SamResourceId: ApiGatewayApi
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/controllers/mediaController.upload
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-stack-bucket
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /media
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/2496cb8a80dd75213520ccfe0fcf7e29
    Metadata:
      SamResourceId: UploadImageFunction
  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/controllers/mediaController.view
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-stack-bucket
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /media/{filename}
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/2496cb8a80dd75213520ccfe0fcf7e29
    Metadata:
      SamResourceId: ViewImageFunction
  SavePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/controllers/photoController.save
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-stack-table-photos
          BUCKET_NAME: nelson-fullstackassignment-stack-bucket
      Events:
        SavePhotoApi:
          Type: Api
          Properties:
            Path: /photo
            Method: post
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/2496cb8a80dd75213520ccfe0fcf7e29
    Metadata:
      SamResourceId: SavePhotoFunction
  ListPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/controllers/photoController.list
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-stack-table-photos
          BUCKET_NAME: nelson-fullstackassignment-stack-bucket
      Events:
        ListPhotoApi:
          Type: Api
          Properties:
            Path: /photo
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/2496cb8a80dd75213520ccfe0fcf7e29
    Metadata:
      SamResourceId: ListPhotoFunction
  DeletePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/controllers/photoController.del
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-stack-table-photos
          BUCKET_NAME: nelson-fullstackassignment-stack-bucket
      Events:
        DeletePhotoApi:
          Type: Api
          Properties:
            Path: /photo/{photoId}
            Method: delete
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/2496cb8a80dd75213520ccfe0fcf7e29
    Metadata:
      SamResourceId: DeletePhotoFunction
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nelson-fullstackassignment-stack-bucket
    Metadata:
      SamResourceId: ImageBucket
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nelson-fullstackassignment-stack-table-photos
      AttributeDefinitions:
      - AttributeName: photoId
        AttributeType: S
      KeySchema:
      - AttributeName: photoId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: PhotosTable
Outputs:
  ImageBucketName:
    Value: nelson-fullstackassignment-stack-bucket
