AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/uploadImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-images-2-bucket
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: post
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/95743d4e0d35a2af2383a648c8eba6f6
    Metadata:
      SamResourceId: UploadImageFunction
  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/viewImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3ReadOnlyAccess
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /viewImage
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/95743d4e0d35a2af2383a648c8eba6f6
    Metadata:
      SamResourceId: ViewImageFunction
  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/deleteImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3FullAccess
      Events:
        DeleteImageApi:
          Type: Api
          Properties:
            Path: /deleteImage
            Method: delete
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/95743d4e0d35a2af2383a648c8eba6f6
    Metadata:
      SamResourceId: DeleteImageFunction
  SavePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/savePhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: PhotosTable
      Events:
        SavePhotoApi:
          Type: Api
          Properties:
            Path: /savePhoto
            Method: post
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/95743d4e0d35a2af2383a648c8eba6f6
    Metadata:
      SamResourceId: SavePhotoFunction
  ListPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/listPhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: PhotosTable
      Events:
        ListPhotoApi:
          Type: Api
          Properties:
            Path: /listPhoto
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/95743d4e0d35a2af2383a648c8eba6f6
    Metadata:
      SamResourceId: ListPhotoFunction
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nelson-images-2-bucket
    Metadata:
      SamResourceId: ImageBucket
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nelson-photo-gallery-table
      AttributeDefinitions:
      - AttributeName: photoId
        AttributeType: S
      KeySchema:
      - AttributeName: photoId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: PhotosTable
Outputs:
  ImageBucketName:
    Value: nelson-images-2-bucket
    Description: Nome do bucket S3 para armazenamento de imagens
