AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'''
      AllowOrigin: '''*'''
      AllowCredentials: '''true'''
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
      - '*~1*'
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
    Metadata:
      SamResourceId: ApiGatewayApi
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/lambda_functions/uploadImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/9d7d731561eb7c4f27e151daf0d787be
    Metadata:
      SamResourceId: UploadImageFunction
  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/lambda_functions/viewImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /viewImage
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/9d7d731561eb7c4f27e151daf0d787be
    Metadata:
      SamResourceId: ViewImageFunction
  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/lambda_functions/deleteImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        DeleteImageApi:
          Type: Api
          Properties:
            Path: /deleteImage
            Method: delete
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/9d7d731561eb7c4f27e151daf0d787be
    Metadata:
      SamResourceId: DeleteImageFunction
  SavePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/lambda_functions/savePhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-table-photos
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        SavePhotoApi:
          Type: Api
          Properties:
            Path: /savePhoto
            Method: post
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/9d7d731561eb7c4f27e151daf0d787be
    Metadata:
      SamResourceId: SavePhotoFunction
  ListPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/lambda_functions/listPhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-table-photos
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        ListPhotoApi:
          Type: Api
          Properties:
            Path: /listPhoto
            Method: get
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-esgfpyjwudyk/9d7d731561eb7c4f27e151daf0d787be
    Metadata:
      SamResourceId: ListPhotoFunction
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nelson-fullstackassignment-bucket
    Metadata:
      SamResourceId: ImageBucket
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nelson-fullstackassignment-table-photos
      AttributeDefinitions:
      - AttributeName: photoId
        AttributeType: S
      KeySchema:
      - AttributeName: photoId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: PhotosTable
Outputs:
  ImageBucketName:
    Value: nelson-fullstackassignment-bucket
