AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    BinaryMediaTypes:
      - "*~1*"

Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/uploadImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: BUCKET_NAME
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: post

  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/viewImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: BUCKET_NAME
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /viewImage
            Method: get

  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/deleteImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: BUCKET_NAME
      Events:
        DeleteImageApi:
          Type: Api
          Properties:
            Path: /deleteImage
            Method: delete

  SavePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/savePhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess 
      Environment:
        Variables:
          TABLE_NAME: TABLE_NAME
          BUCKET_NAME: BUCKET_NAME
      Events:
        SavePhotoApi:
          Type: Api
          Properties:
            Path: /savePhoto
            Method: post

  ListPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/listPhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess 
      Environment:
        Variables:
          TABLE_NAME: TABLE_NAME
      Events:
        ListPhotoApi:
          Type: Api
          Properties:
            Path: /listPhoto
            Method: get
  
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: BUCKET_NAME

  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TABLE_NAME
      AttributeDefinitions:
        - AttributeName: photoId
          AttributeType: S
      KeySchema:
        - AttributeName: photoId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ImageBucketName:
    Value: BUCKET_NAME
