AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors: 
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"
      AllowCredentials: "'true'"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
            - "*~1*"
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/uploadImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

  ViewImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/viewImage.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        ViewImageApi:
          Type: Api
          Properties:
            Path: /viewImage
            Method: get

  SavePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/savePhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess 
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-table-photos
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        SavePhotoApi:
          Type: Api
          Properties:
            Path: /savePhoto
            Method: post

  ListPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/listPhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess 
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-table-photos
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        ListPhotoApi:
          Type: Api
          Properties:
            Path: /listPhoto
            Method: get
  
  DeletePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/deletePhoto.handler
      Runtime: nodejs20.x
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess 
      Environment:
        Variables:
          TABLE_NAME: nelson-fullstackassignment-table-photos
          BUCKET_NAME: nelson-fullstackassignment-bucket
      Events:
        DeletePhotoApi:
          Type: Api
          Properties:
            Path: /deletePhoto/{photoId}
            Method: delete

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nelson-fullstackassignment-bucket

  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nelson-fullstackassignment-table-photos
      AttributeDefinitions:
        - AttributeName: photoId
          AttributeType: S
      KeySchema:
        - AttributeName: photoId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ImageBucketName:
    Value: nelson-fullstackassignment-bucket
